version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ng_assa18
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
      - ./:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
      - ./media:/etc/nginx/media
    depends_on:
      - web
  web:
    build: ./
    container_name: dg_asa18
    command: bash -c "python manage.py collectstatic --noinput && gunicorn asa18.wsgi -b 0.0.0.0:8000"
    ports:
      - "8000"
    volumes:
      - ./:/code
      - ./static:/static
      - ./media:/media
