# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa18', '0081_auto_20180228_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='media',
            field=models.CharField(choices=[(b'n', b'No'), (b'y', b'Yes')], default=b'n', max_length=1),
        ),
    ]
