# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-28 23:31
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asa18', '0082_auto_20180228_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text=b'Detailed description of meeting - you can include sections covering all manner of things, and load in images/Google maps frames etc.'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text=b'Policy content'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='abstract',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text=b'Abstract - LaTeX allowed?'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text=b'About the prize'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='citation',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text=b'Use this field to provide the award citation, as well as give some brief info about the winner'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='honoree_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text=b'Info about who the prize isnamed for'),
        ),
        migrations.AlterField(
            model_name='session',
            name='extended_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text=b'Use this field if a longer description is required, e.g. for a special lunch'),
        ),
    ]
