# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-17 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa18', '0085_auto_20180313_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
