# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-25 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa18', '0086_auto_20180417_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='presentation_hardcopy',
            field=models.FileField(blank=True, help_text=b'Upload a hardcopy of the presentation here for download', null=True, upload_to=b'persentation/%Y/%m/%d/'),
        ),
    ]
